# -*- coding: utf-8 -*-
"""internshiptask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHmvVblEyl6zto4lWY-sZjUbrWLkk7ab
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("/content/API_SP.POP.TOTL_DS2_en_csv_v2_38144.csv",skiprows=4)

population_2020 = data["2020"].dropna()

plt.figure()
plt.hist(population_2020, bins=10,edgecolor="black")
plt.title("Population Distribution (2020)")
plt.xlabel("Population")
plt.ylabel("Number of Countries")
plt.show()

